### ISSUE TITLE
protect the main branch

### ISSUE THREAD

**Issue by Wolverine1122** [BrandoNarv/CEN4020-InCollege-Team-Arizona#1]
@BrandoNarv could you please protect the `main` branch? That way people only make a new branches and can merge to `main` only after review and testing. This help a lot of headache and prevent accidental pushes.

I think prof also mentioned about this briefly. 

There should be a quick guide on how to do this online. I can't do it as I don't have access to repo settings. Thanks!

**Comment by BrandoNarv** [comment]
Solved!
